# Generated by Django 5.2.3 on 2025-06-23 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0003_alter_client_options_alter_mailinglog_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mailings.client', verbose_name='Клиент'),
        ),
    ]
